on:
  pull_request

jobs:

  tests-os:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: pipx install 'poetry>=1.5.0'
      - run: poetry install --sync --no-root || poetry install --sync --no-root
        shell: bash
      - run: poetry run poe check

  markdownlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g markdownlint-cli@0.33.0
      - run: markdownlint . --ignore LICENSE.md
