on:
  pull_request

jobs:
  run-validation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install --remove-untracked
      - run: poetry run poe lint
      - run: poetry run poe test
